version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inputdata
      - MYSQL_USER=croptomize
      - MYSQL_PASSWORD=croptomize
    command: --lower_case_table_names=1